# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_user',
            field=models.ManyToManyField(related_name='wish_user', to='member.Profile'),
        ),
    ]
