# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosting', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_hosting',
            field=models.ManyToManyField(blank=True, related_name='wish_hosting', to='hosting.Hosting'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='member.Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_profile',
            field=models.ManyToManyField(blank=True, related_name='wish_profile', to='member.Profile'),
        ),
    ]
