# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_hosting',
            field=models.ManyToManyField(to='event.Event'),
        ),
    ]
