# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='guestreview',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
