# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171122_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='host',
            new_name='is_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
