# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171210_0733'),
        ('member', '0002_auto_20171210_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_event',
            field=models.ManyToManyField(to='event.Event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wish_hosting',
            field=models.ManyToManyField(to='hosting.Hosting'),
        ),
    ]
