# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_mytrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrip',
            name='user',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
