# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendations',
            field=models.IntegerField(default=0),
        ),
    ]
