# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20171210_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='talent_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
    ]
