# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20171212_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytrip',
            old_name='owner',
            new_name='user',
        ),
    ]
