# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_mytrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_event',
            field=models.ManyToManyField(related_name='wish_event', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wish_hosting',
            field=models.ManyToManyField(related_name='wish_hosting', to='hosting.Hosting'),
        ),
    ]
