# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='참여한 유저 목록'),
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
