# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_images',
            field=models.ManyToManyField(blank=True, related_name='images', to='event.Photo', verbose_name='추가 이미지'),
        ),
    ]
