# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171213_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='event',
            new_name='events',
        ),
    ]
