# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171207_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants_counter',
            new_name='participants_count',
        ),
    ]
