# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171221_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='event_image',
            field=models.ImageField(upload_to='event'),
        ),
    ]
