# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171213_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_photo',
            field=models.ImageField(blank=True, upload_to='event'),
        ),
    ]
