# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171207_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
