# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171221_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphoto',
            old_name='event_image',
            new_name='image',
        ),
    ]
