# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='lat',
            new_name='max_lat',
        ),
        migrations.RenameField(
            model_name='hosting',
            old_name='lon',
            new_name='max_lon',
        ),
        migrations.AddField(
            model_name='hosting',
            name='min_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hosting',
            name='min_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
