# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinfo',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
