# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20171124_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('neighborhood', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.Hosting')),
            ],
        ),
        migrations.RenameField(
            model_name='hostingreview',
            old_name='hosting',
            new_name='place',
        ),
    ]
