# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20171214_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='max_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='hosting',
            old_name='max_lon',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='min_lon',
        ),
    ]
