# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosting', '0002_auto_20171213_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ManyToManyField(to='hosting.Hosting')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
