# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_auto_20171126_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='place',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='place',
        ),
        migrations.AddField(
            model_name='hosting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='exchange',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hosting',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hosting',
            name='neighborhood',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='recommend_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='to_do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosting',
            name='transportation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostingreview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostingreview',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostingreview',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosting.Hosting'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='GeoLocation',
        ),
    ]
