# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_auto_20171127_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosting',
            options={'ordering': ['-has_photo', '-recommend_counter']},
        ),
        migrations.AddField(
            model_name='hosting',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hosting',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=''),
        ),
    ]
