# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_auto_20171127_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='thumbnail',
        ),
    ]
