# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:18
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_remove_hosting_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='thumbnail'),
        ),
    ]
