# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostingreview',
            old_name='writer',
            new_name='author',
        ),
    ]
