# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='hosting')),
                ('type', models.SmallIntegerField(choices=[(1, 'Inside of the house'), (2, 'View of the house'), (3, 'External look of the house'), (4, 'Around the house'), (5, 'Other')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Hosting')),
            ],
        ),
    ]
