# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingreview',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
