# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_hostingreview_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('to_do', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='to_do',
        ),
        migrations.AddField(
            model_name='hosting',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='description',
            name='hosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Hosting'),
        ),
    ]
