# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 02:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userself', to=settings.AUTH_USER_MODEL)),
                ('wish_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_event', to='event.Event')),
                ('wish_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlist 목록',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitems',
            unique_together=set([('user', 'wish_user'), ('user', 'wish_event')]),
        ),
    ]
