# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wish_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_event', to='event.Event'),
        ),
    ]
